### PR TITLE
heading setpoint in float

### PR DESCRIPTION
**Pull request by EwoudSmeur**
related to https://github.com/paparazzi/paparazzi/pull/2051

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
It is not necessary any more to specify alt unit coef for known units: `unit="rad" alt_unit="deg"`

**Comment by flixr** [comment]
IMHO there is no real benefit in changing the ROTORCRAFT_FP `carrot_psi` field to float, it will only make things not work properly anymore if the airborne and ground version are not the same...
For the HOVER_LOOP message I don't really care that much as it is basically only for debugging...

**Comment by podhrmic** [comment]
merging so it works with paparazzi

**Comment by flixr** [comment]
This should have been closed and not merged as it is not needed. Reverting the commit.

**Comment by podhrmic** [comment]
@flixr I merged it because https://github.com/paparazzi/paparazzi/commit/86baffe98a0181afe1d1348c1c44b143cbee4444 changed HOVER_LOOP message, so without this commit it printed warning:

```
firmwares/rotorcraft/guidance/guidance_h.c: In function 'send_hover_loop':
firmwares/rotorcraft/guidance/guidance_h.c:136:28: warning: passing argument 20 of 'pprz_msg_send_HOVER_LOOP' from incompatible pointer type [-Wincompatible-pointer-types]
                            &guidance_h.sp.heading);
                            ^
```

I didn't check it too closely since you already approved it so I thought this is a part of the commit as mentioned.

**Pull request merged**
