### PR TITLE
remote sensors

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by dewagter** [comment]
@fvantienen like this?

**Comment by flixr** [comment]
@dewagter @fvantienen what is the status here?
Do you want this merged, or some other similar branch, or?

**Comment by dewagter** [comment]
@flixr yes it would be great to have it merged

Can it be merged such that commit 428f55753f790f2d4 does not disappear (not
rebase on top of master, but merge or rebase master on top of it)

-Christophe

**Comment by gautierhattenberger** [comment]
rebasing master is not really an option, but I guess we can merge your branch into master this time.

**Pull request merged**
