### PR TITLE
Lidar

### PR DESCRIPTION
**Pull request by podhrmic**
Debug message with LIDAR measurements

### CODE REVIEW

**Comment by podhrmic** [comment]
Merging since Travis is taking forever (validated locally).

**Comment by gautierhattenberger** [comment]
Would still be nice to add some documentation when adding a new message

**Comment by flixr** [comment]
In fact we should make it mandatory....

**Comment by podhrmic** [comment]
Good point. Documentation where? Is there a xml tag for documentation?

**Comment by flixr** [comment]
Yes, there is a `description` xml node for the whole message and docs for fields can be added directly, see some of the other messages (e.g. WIND_INFO_RET)...

**Comment by podhrmic** [comment]
OK, see #27

**Pull request merged**
