### PR TITLE
[message] add a RTOS monitoring message

### PR DESCRIPTION
**Pull request by gautierhattenberger**
usual SYS_MON message doesn't really match RTOS needs

### CODE REVIEW

**Comment by flixr** [comment]
what exactly is th_load supposed to be?

**Comment by gautierhattenberger** [comment]
At least with ChibiOS, I'm evaluating the global CPU load by looking at the time spend in the idle thread. The th_load array just gives the load of the other threads. It gives a hint if one is consuming to much.
Actually I could also send the free stack of each thread, but then I need to change my variable array to 2 fixed arrays, one for load, one for stack.
I should also use a uint16 for the load, otherwise most of them will probably show 0.
The main issue is for sending the thread names. Not really possible at the moment, unless I use the remaining space in the message to send a char[].
If you think it is really useless, I can also remove it.

**Comment by flixr** [comment]
Yeah, was mainly wondering about the association of th_load index and thread name...
So this would be in 0.01 % increments or something like that?
Also is the memory in bytes?

**Comment by gautierhattenberger** [comment]
Memory is in bytes, and could be higher than 2^16. Same for stack size, although none of the stacks are bigger than 2K for now. Should I use uint16 then ?
In the case I use arrays with a fixed length of 20 (uint16 for load, uint32 for stack) (an Apogee with all features can reach 17 threads), it leaves at least 100 bytes, so sending the first 4/5 char of the threads names.

**Comment by flixr** [comment]
Just wondering if we should design the message such that we can also use it for the Linux based systems...

**Comment by gautierhattenberger** [comment]
What would be required to match Linux needs ?

**Comment by flixr** [comment]
I guess that would depend on what information we want to provide...
Right now this could probably already be used since we only have one paparazzi process with multiple threads, except that if the memory is specified in bytes the fields might be too small...

**Comment by gautierhattenberger** [comment]
uint16 or uint32 is too small ? It could be in Kb, but on chibios, our biggest stack is 8K and most of them are less than 1K.

**Comment by flixr** [comment]
If we use uint16_t with unit bytes, we can go up to 64KB... which is clearly not enough on systems running Linux... with uint32_t we could represent up to 512MB, which might or might not be enough...
Or we leave the unit open (e.g. use bytes for small RTOS and KB for linux OSes)

**Comment by gautierhattenberger** [comment]
then, let's say that the unit is the most suitable, e.g. "human readable" option

**Comment by podhrmic** [comment]
Just a thought - I would leave the th_load out, since there doesn't seem to be a nice way to send thread names. That way if you really want to know what each thread is doing you could either use a debugger (for ChibiOS), or SSH in a Linux system (I suppose that would be the case for ArDrone etc?). The rest looks good and would be much simpler/cleaner that way,

**Comment by gautierhattenberger** [comment]
It is also a possibility to just store the information on board (or use linux tools) to get them under debugger. The idea was to have some quick insight of the problem.
So @flixr @podhrmic should I leave the arrays out or keep them in the message ?
It can be added/removed later anyway.

**Comment by flixr** [comment]
I wouldn't mind keeping th_load without the thread names if the order of the reported threads stays the same, since as you said that can already give some quick insight at a glance...
But I have no strong opinion here...

**Comment by podhrmic** [comment]
I would prefer leaving it out, since the threads can change in future (their names/order).

**Comment by gautierhattenberger** [comment]
Ok, removed it then.
Since the data will be available internally, we can change our mind, debugging is rather easy otherwise.

**Comment by gautierhattenberger** [comment]
can I merge like this ?

**Comment by flixr** [comment]
maybe specify the unit used for memory?
otherwise looks good to me!

**Pull request merged**
