### PR TITLE
Added wing position message

### PR DESCRIPTION
**Pull request by kevindehecker**

### CODE REVIEW

**Comment by gautierhattenberger** [comment]
Can you explain a bit the use case and also add a description to the message. thanks

**Comment by kevindehecker** [comment]
Added description, the use case is described here: https://github.com/paparazzi/paparazzi/pull/2016

**Comment by flixr** [comment]
For what is that message actually used? Just for debugging?
Maybe we can find a more generic message so we don't need to add messages for only one very specific airframe and use case?

**Comment by kevindehecker** [comment]
I could not find a generic one, but I did not look hard.

It is used to tune the exact position of where the wing has to stop & lock to perform optimal glide. This probably has to be tuned for each Robird-like airframe (but currently I only have one).

**Comment by kevindehecker** [comment]
So, is it acceptable like this? Or do I need to hack it in some existing message?

**Comment by flixr** [comment]
Since you are only transmitting an ADC value, why not use the ADC message?

**Comment by kevindehecker** [comment]
Because, at some point, I was planning to convert the value to a wing angle. But fine, since it seems to be problematic to add a message and it's not that important I will do that!

**Comment by gautierhattenberger** [comment]
Just in case you need to send a bunch of data for debugging, you can also use the PAYLOAD message (byte array) or PAYLOAD_FLOAT (float array)

**Comment by flixr** [comment]
Or if its really only for debugging you can even use INFO_MSG to send a string which will also display it in the GCS console...

**Pull request closed without merging**
