### PR TITLE
Added visual select message

### PR DESCRIPTION
**Pull request by rmeertens**
Will be used to click on objects in the video stream. Will later push the viewer that uses this feature once it is bugfree

### CODE REVIEW

**Comment by flixr** [comment]
Can you please add a description of the message and fields?
Also if you use "broadcasted" it will go to all drones... probably makes more sense to add an `ac_id` and use "forwarded"?

**Comment by rmeertens** [comment]
Done.

**Comment by gautierhattenberger** [comment]
actually if you make the description inside `field` node like https://github.com/paparazzi/pprzlink/blob/master/message_definitions/v1.0/messages.xml#L2470, it will be in the generated documentation (http://docs.paparazziuav.org/latest/paparazzi_messages.html#GUIDED_SETPOINT_NED)

**Comment by flixr** [comment]
Please add the description not as a comment, but like in e.g. https://github.com/paparazzi/pprzlink/blob/master/message_definitions/v1.0/messages.xml#L1108

Also maybe we should name this something like IMAGE/VIDEO_ROI (RegionOfInterest)?

Still unclear to me what you want to do with the message once you receive it on the drone...

**Comment by rmeertens** [comment]
Nice. I did not know that. 
Potential use cases: 
- follow me drone (I already made this). Example of Phantom doing the same: see here: https://www.youtube.com/watch?v=LJx1z7d7oQ4
- select what region you want your drone to explore
- Select a region to zoom in.

**Comment by flixr** [comment]
Please fix the message...

Also I would propose to name this message VIDEO_ROI instead of VIDEO_SELECTED

Let my make my previous question clear: how you want to decide between the different actions when receiving this message...
Do we need to add some sort of cmd_id/action_id? Or is it simply defined by which (and only one) module you have loaded that listens to this message?

**Comment by rmeertens** [comment]
Repaired and renamed. 

Selecting a region as an action.... and this is the only action that is possible...
Every module that would be interested in this information can start listening to this message...

You probably have other actions in mind, such as VIDEO_CLICKED. I would make this another kind of message... Shall I add it for this pull request?

**Comment by flixr** [comment]
Thanks.
Looks good to merge to me now, we can still add an cmd/id or whatever later if needed.
You might want to specify multiple ROI in an image...

And No, I definitely didn't have something like VIDEO_CLICKED in mind...
IMHO that would be a poor abstraction, on the airborne side you don't care if someone clicked on the video, typed it in or gave a voice command... it's the abstract action/cmd that counts, not what input was used to create that command.

**Pull request merged**
