### PR TITLE
added flask server

### PR DESCRIPTION
**Pull request by rmeertens**
Not sure about the PPRZ path to use.

### CODE REVIEW

**Comment by flixr** [comment]
IMHO this needs some more work...

* make flaskserver.py executable
* use `if __name__ == "__main__"` and call `interface.shutdown()` at the end
* fix path to something like in ivy_msg_interface.py
* short explanation on root page with links to available subpages?
* at least a README which describes dependencies and usage

**Comment by flixr** [comment]
also it might be nicer to add stuff like this to an `examples` folder instead of tools, especially if it's still basic

**Comment by podhrmic** [comment]
Is this still relevant or shall we close it? @rmeertens @flixr

**Comment by rmeertens** [comment]
Nope, let's leave it out!

**Pull request closed without merging**
