### PR TITLE
Add short transport for C

### PR DESCRIPTION
**Pull request by dewagter**

### CODE REVIEW

**Comment by flixr** [comment]
What is the use-case for this?

**Comment by dewagter** [comment]
this was the use case: https://github.com/paparazzi/paparazzi/pull/1821

**Comment by fvantienen** [comment]
It is basically to have no extra overhead when transmitting telemetry over a good link. So for example with intermcu we repack this message again over a new intermcu telemetry message. Which already has a checksum etc.

**Comment by flixr** [comment]
Ok, makes sense... would have been nice to put that in the description ;-)

**Pull request merged**
